const pageItems = [
    { label: "Giriş Sayfası", uri: "/"},
    { label: "Ürünler", uri: "/catalogue/yuksek-performansli-dpf-twc"},
    { label: "PRISTA", uri: "/catalogue/yuksek-performansli-dpf-twc"},
    { label: "Pazarlar", uri: "/istirakler"},
    { label: "İştirakler", uri: "/istirakler"},
    { label: "Distribütörler", uri: "/distributorler"},
    { label: "Kalite Yönetimi", uri: "/teknoloji-merkezi"},
    { label: "Teknoloji merkezi", uri: "/teknoloji-merkezi"},
    { label: "Laboratuvar servisleri", uri: "/laboratuvar-servisleri"},
    { label: "Prista sertifikaları", uri: "/prista-sertifikalari"},
    { label: "Bizimle temasa geçin", uri: "/bizimle-temasa-gecin"},
    { label: "Medya", uri: "/news/category/bayilik-hakkinda-1"},
    { label: "Bayilik Hakkinda", uri: "/news/category/bayilik-hakkinda-1"},
    { label: "Haberler", uri: "/news/category/haberler"},
    { label: "Hakkımızda", uri: "/biz-kimiz"},
    { label: "Biz kimiz", uri: "/biz-kimiz"},
    { label: "Ortaklarımız", uri: "/ortaklarimiz"},
    { label: "Şirketin sorumluluğu", uri: "/sirketin-sorumlulugu"},
    { label: "Gizlilik politikası", uri: "/gizlilik-politikasi"},
    { label: "Çerez politikası", uri: "/cerez-politikasi"},
    { label: "İrtibat", uri: "/harita"},
    { label: "Nereden satın alabiliriz?", uri: "/distributorler"},
];

export default pageItems;