const productItems = [
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-plus-5w-30-4", label: "Prista Ultra Plus 5W-30" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-rn-5w-30-4", label: "Prista Ultra RN 5W-30" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-v-5w-30-4", label: "Prista Ultra V 5W-30" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-g-5w-30-4", label: "Prista Ultra G 5W-30" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-plus-5w-40-4", label: "Prista Ultra Plus 5W-40" },
    { uri: "/catalogue/yuksek-performansli/prista-ultra-5w-30-5w-40-4", label: "Prista Ultra  5W-30/ 5W-40" },
    { uri: "/catalogue/yuksek-performansli/prista-leader-10w-40-6", label: "Prista Leader 10W-40" },
    { uri: "/catalogue/yuksek-performansli/prista-super-benzin-10w-40-4", label: "Prista Super Benzin 10W-40" },
    { uri: "/catalogue/standart/prista-super-hd-10w-40-4", label: "Prista Super HD 10W-40" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc-uyumlu/prista-uhpd-5w-30-4", label: "Prista UHPD 5W-30" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc-uyumlu/prista-uhpd-10w-40-4", label: "Prista UHPD 10W-40" },
    { uri: "/catalogue/yuksek-performansli-1/prista-ultra-td-10w-40-4", label: "Prista Ultra TD 10W-40" },
    { uri: "/catalogue/yuksek-performansli-1/prista-shpd-vds-3-10w-40-4", label: "Prista SHPD VDS-3 10W-40" },
    { uri: "/catalogue/yuksek-performansli-1/prista-shpd-ls-15w-40-6", label: "Prista SHPD LS 15W-40" },
    { uri: "/catalogue/ustun-1/prista-shpd-vds-3-15w-40-20w-50-4", label: "Prista SHPD VDS-3 15W-40/ 20W-50" },
    { uri: "/catalogue/ustun-1/prista-turbo-diesel-15w-40-20w-50-4", label: "Prista Turbo Diesel 15W-40/ 20W-50" },
    { uri: "/catalogue/ustun-1/prista-r-leader-15w-40-20w-50-6", label: "Prista® Leader 15W-40/ 20W-50" },
    { uri: "/catalogue/standart-1/prista-super-hd-15w-40-20w-50-9", label: "Prista Super HD 15W-40/ 20W-50" },
    { uri: "/catalogue/gaz-motor-yaglari/prista-multigas-hd-15w-40-4", label: "Prista Multigas HD 15W-40" },
    { uri: "/catalogue/2t-4t-yaglari/prista-2t-extra-4", label: "Prista 2T Extra" },
    { uri: "/catalogue/2t-4t-yaglari/prista-2t-mix-4", label: "Prista 2T Mix" },
    { uri: "/catalogue/2t-4t-yaglari/prista-r-4t-6", label: "Prista® 4T" },
    { uri: "/catalogue/2t-4t-yaglari/prista-2t-outboard-4", label: "Prista 2T-Outboard" },
    { uri: "/catalogue/yuksek-performansli-duz-sanziman/prista-ultragear-synthetic-75w-80-75w-90-4", label: "Prista Ultragear Synthetic 75W-80/  75W-90" },
    { uri: "/catalogue/yuksek-performansli-otomatik-sanziman/prista-atf-iii-4", label: "Prista ATF III" },
    { uri: "/catalogue/yuksek-performansli-otomatik-sanziman/prista-atf-4", label: "Prista ATF" },
    { uri: "/catalogue/yuksek-performansli-otomatik-sanziman/prista-mhp-40a-4", label: "Prista MHP 40A" },
    { uri: "/catalogue/yuksek-performansli-otomatik-sanziman/prista-mhp-32-4", label: "Prista MHP 32" },
    { uri: "/catalogue/yuksek-performansli-otomatik-sanziman/prista-psf-4", label: "Prista PSF" },
    { uri: "/catalogue/duz-sanziman-ve-aks/prista-ep-sae-90-140-4", label: "Prista EP SAE 90/140" },
    { uri: "/catalogue/duz-sanziman-ve-aks/prista-ep-sae-80w-90-85w-90-85w-140-4", label: "Prista EP SAE 80W-90/85W-90/ 85W-140" },
    { uri: "/catalogue/duz-sanziman-ve-aks/prista-gl4-sae-90-4", label: "Prista GL4 SAE 90" },
    { uri: "/catalogue/utto-stou-to-4-5/prista-r-stou-4", label: "Prista® STOU" },
    { uri: "/catalogue/utto-stou-to-4-5/prista-r-utto-3", label: "Prista® UTTO" },
    { uri: "/catalogue/utto-stou-to-4-5/prista-to-4-sae-10w-30-4", label: "Prista TO-4 SAE 10W /30" },
    { uri: "/catalogue/sogutma-sulari/prista-antifreeze-long-life-4", label: "Prista Antifreeze Long Life" },
    { uri: "/catalogue/ozel-akiskanlar/prista-antifreeze-long-life-ready-to-use-4", label: "Prista Antifreeze Long Life (ready-to-use)" },
    { uri: "/catalogue/sogutma-sulari/prista-antifreeze-concentrate-4", label: "Prista Antifreeze Concentrate" },
    { uri: "/catalogue/sogutma-sulari/prista-antifreeze-4", label: "Prista Antifreeze" },
    { uri: "/catalogue/fren-hidrolikleri/prista-dot-4-dot-3-4", label: "Prista DOT-4/ DOT-3" },
    { uri: "/catalogue/on-cam-yikama-sivilari/prista-screenwash-summer-4", label: "Prista Screenwash Summer" },
    { uri: "/catalogue/on-cam-yikama-sivilari/prista-screenwash-winter-4", label: "Prista Screenwash Winter" },
    { uri: "/catalogue/adblue-r-6/adblue-6", label: "AdBlue®" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhv-plus-4", label: "Prista MHV Plus" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhv-7", label: "Prista MHV" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhm-plus-4", label: "Prista MHM Plus" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhm-4", label: "Prista MHM" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhm-b-4", label: "Prista MHM-b" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhm-d-4", label: "Prista MHM-D" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-bio-mhm-46-4", label: "Prista Bio MHM-46" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhl-4", label: "Prista MHL" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-fd-5-4", label: "Prista FD 5" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mhe-40-4", label: "Prista MHE-40" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-shock-absorber-oil-4", label: "Prista Shock Absorber Oil" },
    { uri: "/catalogue/hidrolik-ve-kizak-yaglari/prista-mnp-4", label: "Prista MNP" },
    { uri: "/catalogue/kompresor-yaglari/prista-r-compressor-synth-4", label: "Prista® Compressor Synth" },
    { uri: "/catalogue/kompresor-yaglari/prista-mvk-2-7", label: "Prista MVK 2" },
    { uri: "/catalogue/kompresor-yaglari/prista-mvk-1-4", label: "Prista MVK 1" },
    { uri: "/catalogue/kompresor-yaglari/prista-frigus-ha-7", label: "Prista Frigus HA" },
    { uri: "/catalogue/endustriyel-disli-yaglari/prista-rolon-f-4", label: "Prista Rolon F" },
    { uri: "/catalogue/endustriyel-disli-yaglari/prista-rolon-7", label: "Prista Rolon" },
    { uri: "/catalogue/turbin-yaglari/prista-tpx-7", label: "Prista Tpx" },
    { uri: "/catalogue/turbin-yaglari/prista-tps-32-4", label: "Prista Tps -32" },
    { uri: "/catalogue/turbin-yaglari/prista-tps-46-4", label: "Prista Tps -46" },
    { uri: "/catalogue/turbin-yaglari/prista-tps-ep-7", label: "Prista Tps EP" },
    { uri: "/catalogue/turbin-yaglari/prista-tp-4", label: "Prista Tp" },
    { uri: "/catalogue/turbin-yaglari/prista-tps-68", label: "Prista Tps-68" },
    { uri: "/catalogue/transformator-yaglari/prista-trafo-a-hosio-4", label: "Prista Trafo A HOSIO" },
    { uri: "/catalogue/transformator-yaglari/prista-trafo-a-4", label: "Prista Trafo A" },
    { uri: "/catalogue/transformator-yaglari/prista-trafo-4", label: "Prista Trafo" },
    { uri: "/catalogue/sirkulasyon-yaglari-ve-genel-amacli-yaglar/prista-paper-machine-4", label: "Prista Paper Machine" },
    { uri: "/catalogue/sirkulasyon-yaglari-ve-genel-amacli-yaglar/prista-circulating-oil-4", label: "Prista Circulating Oil" },
    { uri: "/catalogue/sirkulasyon-yaglari-ve-genel-amacli-yaglar/prista-an-4", label: "Prista AN" },
    { uri: "/catalogue/motorlu-testere-yaglari/prista-mvr-multi-4", label: "Prista MVR Multi" },
    { uri: "/catalogue/motorlu-testere-yaglari/prista-mvr-4", label: "Prista MVR" },
    { uri: "/catalogue/isi-transfer-yaglari/prista-supertherm-22-4", label: "Prista Supertherm 22" },
    { uri: "/catalogue/isi-transfer-yaglari/prista-mtl-7", label: "Prista MTL" },
    { uri: "/catalogue/isi-transfer-yaglari/prista-eco-heat-fluid-4", label: "Prista Eco Heat Fluid" },
    { uri: "/catalogue/su-verme-yaglari/prista-mz-e-4", label: "Prista MZ-E" },
    { uri: "/catalogue/su-verme-yaglari/prista-mz-4", label: "Prista MZ" },
    { uri: "/catalogue/sade-yaglar/prista-rezinol-hd-22-4", label: "Prista Rezinol HD 22" },
    { uri: "/catalogue/sade-yaglar/prista-rezinol-4", label: "Prista Rezinol" },
    { uri: "/catalogue/sade-yaglar/prista-c-4", label: "Prista C" },
    { uri: "/catalogue/sade-yaglar/prista-frezol-ep-4", label: "Prista Frezol EP" },
    { uri: "/catalogue/sade-yaglar/prista-frezol-4", label: "Prista Frezol" },
    { uri: "/catalogue/sade-yaglar/prista-mpd-4", label: "Prista MPD" },
    { uri: "/catalogue/sade-yaglar/prista-ee-5-4", label: "Prista EE 5" },
    { uri: "/catalogue/sade-yaglar/prista-honing-4", label: "Prista HONING" },
    { uri: "/catalogue/suda-cozulebilir/prista-synthilin-5-4", label: "Prista Synthilin 5" },
    { uri: "/catalogue/suda-cozulebilir/prista-synthol-a-hw-4", label: "Prista Synthol A-HW" },
    { uri: "/catalogue/suda-cozulebilir/prista-synthol-a-sw-4", label: "Prista Synthol A-SW" },
    { uri: "/catalogue/suda-cozulebilir/prista-emulsin-extra-4", label: "Prista Emulsin Extra" },
    { uri: "/catalogue/suda-cozulebilir/prista-emulsol-ab-4", label: "Prista Emulsol AB" },
    { uri: "/catalogue/suda-cozulebilir/prista-emulsol-b-4", label: "Prista Emulsol B" },
    { uri: "/catalogue/plastiklestiriciler/prista-pk-4", label: "Prista PK" },
    { uri: "/catalogue/kalip-ayirma-yaglari/prista-km-4", label: "Prista KM" },
    { uri: "/catalogue/sabit-gaz-motorlari/prista-gmk-4", label: "Prista GMK" },
    { uri: "/catalogue/sabit-gaz-motorlari/prista-r-ngeo-40-4", label: "Prista® NGEO 40" },
    { uri: "/catalogue/sistem-yaglari/465", label: "Prista Marine C" },
    { uri: "/catalogue/kovan-pistonlu-motor-yaglari/prista-marine-d-3", label: "Prista Marine D" },
    { uri: "/catalogue/kovan-pistonlu-motor-yaglari/prista-marine-ds-3", label: "Prista Marine DS" },
    { uri: "/catalogue/kovan-pistonlu-motor-yaglari/prista-marine-s-3", label: "Prista Marine S" },
    { uri: "/catalogue/kovan-pistonlu-motor-yaglari/prista-marine-st-3", label: "Prista Marine ST" },
    { uri: "/catalogue/silindir-yaglari/prista-marine-cm-3", label: "Prista Marine CM" },
    { uri: "/catalogue/disli-yaglari/prista-rolon-8", label: "Prista Rolon" },
    { uri: "/catalogue/sogutma-sistemi-yagi/prista-frigus-ha-8", label: "Prista Frigus HA" },
    { uri: "/catalogue/kompresor-yaglari-1/prista-mvk-2-8", label: "Prista MVK-2" },
    { uri: "/catalogue/isi-transfer-yagi/prista-mtl-8", label: "Prista MTL" },
    { uri: "/catalogue/turbin-yaglari-1/prista-tpx-8", label: "Prista TPx" },
    { uri: "/catalogue/turbin-yaglari-1/prista-tps-ep-8", label: "Prista TPs EP" },
    { uri: "/catalogue/hidrolik-yaglar/prista-mhv-8", label: "Prista MHV" },
    { uri: "/catalogue/motor-yaglari/prista-shpd-vds-3-3", label: "Prista SHPD VDS-3" },
    { uri: "/catalogue/gresler-1/prista-lithium-ep-3", label: "Prista Lithium EP" },
    { uri: "/catalogue/gresler-1/prista-lithium-lix-ep2-3", label: "Prista Lithium LiX EP2" },
    { uri: "/catalogue/gresler-1/prista-limo-2", label: "Prista LiMo" },
    { uri: "/catalogue/gresler-1/prista-k-g-2", label: "Prista K-G" },
    { uri: "/catalogue/havoline-ultra-6/havoline-ultra-s-5w-30-6", label: "Havoline Ultra S 5W-30" },
    { uri: "/catalogue/havoline-energy-6/havoline-energy-ef-sae-5w-30-6", label: "Havoline Energy EF SAE 5W-30" },
    { uri: "/catalogue/havoline-energy-6/havoline-energy-ms-sae-5w-30-6", label: "Havoline Energy MS SAE 5W-30" },
    { uri: "/catalogue/havoline-ultra-6/havoline-ultra-sae-5w-40-6", label: "Havoline Ultra SAE 5W-40" },
    { uri: "/catalogue/havoline-ultra-6/havoline-ultra-r-5w-30-6", label: "Havoline Ultra R 5W-30" },
    { uri: "/catalogue/havoline-energy-6/havoline-energy-sae-0w-30-6", label: "Havoline Energy SAE 0W-30" },
    { uri: "/catalogue/havoline-energy-6/havoline-energy-sae-0w-20-6", label: "Havoline Energy SAE 0W-20" },
    { uri: "/catalogue/havoline-energy-6/havoline-energy-sae-5w-30-6", label: "Havoline Energy SAE 5W-30" },
    { uri: "/catalogue/havoline-extra-6/havoline-extra-sae-10w-40-6", label: "Havoline Extra SAE 10W-40" },
    { uri: "/catalogue/havoline-extra-6/havoline-extra-sae-15w-40-6", label: "Havoline Extra SAE 15W-40" },
    { uri: "/catalogue/2t-4t-yaglari-1/havoline-4t-motorcycle-oil-sae-10w-40-6", label: "Havoline 4T Motorcycle Oil SAE 10W-40" },
    { uri: "/catalogue/2t-4t-yaglari-1/havoline-super-2t-sx-6", label: "Havoline Super 2T-SX" },
    { uri: "/catalogue/2t-4t-yaglari-1/havoline-super-2t-x-6", label: "Havoline Super 2T-X" },
    { uri: "/catalogue/otomatik-sanziman-yaglari-1/havoline-full-synthetic-multi-vehicle-atf-6", label: "Havoline Full Synthetic Multi-Vehicle ATF" },
    { uri: "/catalogue/otomatik-sanziman-yaglari-1/havoline-multi-vehicle-atf-7", label: "Havoline Multi-Vehicle ATF" },
    { uri: "/catalogue/disli-yaglari-1/geartex-s4-6", label: "Geartex S4" },
    { uri: "/catalogue/disli-yaglari-1/geartex-ls-6", label: "Geartex LS" },
    { uri: "/catalogue/disli-yaglari-1/multigear-rn-premium-sae-75w-80-6", label: "Multigear RN Premium SAE 75W-80" },
    { uri: "/catalogue/disli-yaglari-1/geartex-ep-b-6", label: "Geartex EP-B" },
    { uri: "/catalogue/disli-yaglari-1/geartex-ep-c-6", label: "Geartex EP-C" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-p-sae-0w-30-6", label: "Havoline ProDS P SAE 0W-30" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-m-sae-5w-30-6", label: "Havoline ProDS M SAE 5W-30" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-f-sae-5w-20-6", label: "Havoline ProDS F SAE 5W-20" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-v-sae-5w-30-6", label: "Havoline ProDS V SAE 5W-30" },
    { uri: "/catalogue/disli-yaglari-1/multigear-sae-80w-90-6", label: "Multigear SAE 80W-90" },
    { uri: "/catalogue/gresler-3/hytex-ep-2-lf-6", label: "Hytex EP 2 LF" },
    { uri: "/catalogue/gresler-3/starplex-ep-2-6", label: "Starplex EP 2" },
    { uri: "/catalogue/gresler-3/multifak-ep-2-6", label: "Multifak EP 2" },
    { uri: "/catalogue/gresler-3/copper-grease-9143-13", label: "Copper Grease 9143" },
    { uri: "/catalogue/gresler/prista-r-cs-complex-ep-2-1-5-7", label: "Prista® CS Complex EP 2 /1.5" },
    { uri: "/catalogue/gresler/prista-r-li-complex-ep-2-hdvt-7", label: "Prista® Li Complex EP 2 HDVT*" },
    { uri: "/catalogue/gresler/prista-r-li-complex-ep-2-7", label: "Prista® Li Complex EP 2" },
    { uri: "/catalogue/gresler/prista-r-lithium-ep-7", label: "Prista® Lithium EP" },
    { uri: "/catalogue/gresler/prista-r-lithium-ep-0-00-7", label: "Prista® Lithium EP 0/00" },
    { uri: "/catalogue/gresler/prista-r-limo-ep-prista-r-limo-ep-2-g-7", label: "Prista® LiMo EP &amp; Prista® LiMo EP 2 G" },
    { uri: "/catalogue/gresler/prista-r-lithium-7", label: "Prista® Lithium" },
    { uri: "/catalogue/gresler/prista-r-lica-7", label: "Prista® LiCa" },
    { uri: "/catalogue/gresler/prista-r-lica-ep-2-7", label: "Prista® LiCa  EP 2" },
    { uri: "/catalogue/gresler/prista-r-k-2-g-vs-prista-r-k-2-g-7", label: "Prista® K-2-G VS* &amp; Prista® K-2-G" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-fe-5w-30-7", label: "Prista Ultra FE 5W-30" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-gf-0w-20-7", label: "Prista Ultra GF 0W-20" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-fe-0w-30-7", label: "Prista Ultra FE 0W-30" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-ultra-c5-0w-20-7", label: "Prista Ultra C5 0W-20" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc-uyumlu/prista-shpd-ls-10w-30-7", label: "Prista SHPD LS 10W-30" },
    { uri: "/catalogue/ustun/prista-leader-15w-40-20w-50-7", label: "Prista Leader 15W-40/20W-50" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-f-sae-0w-30-7", label: "Havoline ProDS F SAE 0W-30" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-vb-sae-0w-20-7", label: "Havoline ProDS VB SAE 0W-20" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-vb-sae-0w-20-new-formulation-7", label: "Havoline ProDS VB SAE 0W-20 (New formulation)" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-rn-sae-0w-20-7", label: "Havoline ProDS RN SAE 0W-20" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-rn-sae-5w-30-7", label: "Havoline ProDS RN SAE 5W-30" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-mg-sae-0w-20-7", label: "Havoline ProDS MG SAE 0W-20" },
    { uri: "/catalogue/havoline-prods-6/havoline-prods-v-sae-0w-30-7", label: "Havoline ProDS V SAE 0W-30" },
    { uri: "/catalogue/havoline-ultra-6/havoline-ultra-0w-20-7", label: "Havoline Ultra 0W-20" },
    { uri: "/catalogue/havoline-ultra-6/havoline-ultra-0w-30-7", label: "Havoline Ultra 0W-30" },
    { uri: "/catalogue/havoline-ultra-6/havoline-ultra-a-5w-40-7", label: "Havoline Ultra А 5W-40" },
    { uri: "/catalogue/2t-4t-yaglari-1/havoline-outboard-2t-7", label: "Havoline Outboard 2T" },
    { uri: "/catalogue/antifriz-sogutma-sivilari/havoline-xtended-life-antifreeze-coolant-7", label: "Havoline Xtended Life Antifreeze/Coolant" },
    { uri: "/catalogue/antifriz-sogutma-sivilari/havoline-xli-7", label: "Havoline XLI" },
    { uri: "/catalogue/antifriz-sogutma-sivilari/havoline-ghc-pre-mixed-50-50-7", label: "Havoline GHC Pre-Mixed 50/50" },
    { uri: "/catalogue/yuksek-performansli-otomatik-sanziman/prista-r-atf-ii-m-4", label: "PRISTA® ATF II M" },
    { uri: "/catalogue/gresler/prista-r-li-complex-ep-2-ptfe-green-4", label: "PRISTA®  Li Complex EP 2 PTFE Green" },
    { uri: "/catalogue/gresler/prista-r-k-3-4", label: "PRISTA® K-3" },
    { uri: "/catalogue/gresler/prista-r-lithium-2-5", label: "PRISTA® Lithium 2" },
    { uri: "/catalogue/gresler/prista-r-lithium-ep-2-5", label: "PRISTA® Lithium EP 2" },
    { uri: "/catalogue/gresler/prista-r-syntech-ep-2-4", label: "PRISTA® Syntech EP 2" },
    { uri: "/catalogue/yuksek-performansli-dpf-twc/prista-r-ultra-v-0w-20-4", label: "PRISTA® Ultra V 0W-20" },
];

export default productItems;